# Generated by Django 3.2.9 on 2021-11-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
